language: generic

udo: required

services:
  - docker

before_install:
  - docker build -t brisgi/docker-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true brisgi/docker-test npm run test

after_success:
  - docker build -t brisgi/docker-frontend ./frontend
  - docker build -t brisgi/docker-backend ./backend
  - docker build -t brisgi/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push brisgi/docker-frontend
  - docker push brisgi/docker-backend
  - docker push brisgi/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack"
  env: "DockerFullstack-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-480504116656
  bucket_path: "docker-fullstack"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
